version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_USER: umorryie
      MYSQL_DATABASE: fitness
      MYSQL_PASSWORD: secretpassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"